.\" Manpage for cdc.
.\" Contact sqp@glx-dock.org to correct errors or typos.
.TH man 8 "17 Aug 2015" "0.0.3.3" "cdc man page"
.SH NAME
cdc \- start a dock/panel desktop interface
.SH SYNOPSIS
cdc [help]
.SH DESCRIPTION
cdc is highly configurable dock/panel interface able to be a nice main or second desktop controller.
It comes with a bunch of applets to fill all your interactions needs.
.SH OPTIONS
The program has a log of options and subcommands that can be displayed using cdc help.
.SH SEE ALSO
cairo-dock(1)
.SH BUGS
To prevent any disk space problem, the bugs list has not been written.
.SH AUTHOR
SQP (sqp@glx-dock.org)